apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prometheus-data
  namespace: observability
  labels:
    app: prometheus-deployment
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/observability/prometheus"
