apiVersion: v1
kind: ConfigMap  
metadata:
  name: grafana-env
  namespace: plant-iccp
data:
  GF_LIVE_MAX_CONNECTIONS: "0"
  GF_SECURITY_ALLOW_EMBEDDING: "true"
  GF_SERVER_ROOT_URL: "http://grafana:3000/api/grafana"
  GF_SERVER_SERVE_FROM_SUB_PATH: "true"