apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: plant-iccp
data:
  prometheus.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "access":"proxy",
                "editable": true,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus-service.plant-iccp.svc:8080",
                "version": 1
            }
        ]
    }
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
               "GF_LIVE_MAX_CONNECTIONSGF_LIVE_MAX_CONNECTIONS":0,
               "GF_SECURITY_ALLOW_EMBEDDING":"true",
               "GF_SERVER_ROOT_URL":"http://grafana:3000/api/grafana"
               "GF_SERVER_SERVE_FROM_SUB_PATH":"true"
            }
        ]
    }   
